import { getUser, ratingClass } from '@/lib/data';
export default async function Stats(){
 const {supabase,user}=await getUser();if(!user)return null;
 const {data:team}=await supabase.from('match_team_stats').select('*').eq('user_id',user.id);
 const {data:matches}=await supabase.from('matches').select('id,team_rating').eq('user_id',user.id);
 const {data:players}=await supabase.from('players').select('id,name,short_name,position,number').eq('user_id',user.id).eq('active',true);
 const {data:ratings}=await supabase.from('match_players').select('player_id,user_rating').eq('user_id',user.id).not('user_rating','is',null);
 const {data:ps}=await supabase.from('player_match_stats').select('*').eq('user_id',user.id);
 const nums=(key:string)=> (team??[]).map((x:any)=>Number(x[key])).filter((n:number)=>Number.isFinite(n)); const sum=(key:string)=>nums(key).reduce((a,b)=>a+b,0); const mean=(key:string)=>{const a=nums(key);return a.length?(a.reduce((x,y)=>x+y,0)/a.length).toFixed(1):'—'};
 const map=new Map<string,number[]>();(ratings??[]).forEach(r=>{const a=map.get(r.player_id)??[];a.push(Number(r.user_rating));map.set(r.player_id,a)});
 const totals=new Map<string,any>();(ps??[]).forEach((s:any)=>{const t=totals.get(s.player_id)||{appearances:0,minutes:0,goals:0,assists:0,shots:0,shots_on_target:0,successful_dribbles:0,duels_won:0,recoveries:0,yellow_cards:0,red_cards:0};for(const k of Object.keys(t))if(k!=='player_id')t[k]+=Number(s[k]||0);totals.set(s.player_id,t)});
 const ranking=(players??[]).map(p=>{const a=map.get(p.id)??[];return {...p,avg:a.length?a.reduce((x,y)=>x+y,0)/a.length:null,total:totals.get(p.id)||{}}}).sort((a,b)=>(b.avg??-1)-(a.avg??-1));
 return <div><header className="topbar"><div><p className="eyebrow">STATISTICHE</p><h1>Analisi</h1><p className="muted">Dati automatici + voti personali, aggregati dalla stagione sincronizzata.</p></div></header><section className="stat-grid"><div className="stat-card"><span>Gol</span><strong>{sum('goals')}</strong><small>team</small></div><div className="stat-card"><span>xG</span><strong>{sum('xg').toFixed(2)}</strong><small>team</small></div><div className="stat-card"><span>Possesso</span><strong>{mean('possession')}{mean('possession')!=='—'?'%':''}</strong><small>media</small></div><div className="stat-card"><span>Pass accuracy</span><strong>{mean('pass_accuracy')}{mean('pass_accuracy')!=='—'?'%':''}</strong><small>media</small></div></section><section className="panel"><div className="panel-head"><div><p className="eyebrow">RANKING</p><h3>Giocatori per tua media</h3></div><span className="muted">{matches?.length??0} partite</span></div>{ranking.map((p,i)=><div className="rank-row" key={p.id}><span className="rank">{i+1}</span><span className="avatar">{p.number??'—'}</span><div className="player-info"><b>{p.name}</b><small>{p.position??''} · {p.total.appearances??0} presenze</small></div><div className="rank-track"><i style={{width:`${Math.max(0,Math.min(100,(p.avg??0)*10))}%`}}/></div><strong className={p.avg?ratingClass(p.avg):''}>{p.avg?p.avg.toFixed(1):'—'}</strong></div>)}{!ranking.length&&<p className="empty">Le statistiche appariranno dopo la sincronizzazione.</p>}</section></div>
}
