import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

const API='https://site.api.espn.com/apis/site/v2/sports/soccer';
const JUVE_ID='111';
const LEAGUES=['ita.1','uefa.champions','uefa.europa','ita.coppa_italia','ita.supercoppa'];

type Any=any;
async function get(path:string){
  const r=await fetch(API+path,{cache:'no-store'});
  const b=await r.json().catch(()=>({}));
  if(!r.ok) throw new Error(`ESPN HTTP ${r.status}`);
  return b;
}
function arr(v:Any){return Array.isArray(v)?v:[]}
function num(v:Any){const n=Number(v);return Number.isFinite(n)?n:null}
function text(v:Any){return v==null?'':String(v)}
function teamId(t:Any){return text(t?.id||t?.team?.id)}
function isJuve(t:Any){return teamId(t)===JUVE_ID||/juventus/i.test(text(t?.displayName||t?.team?.displayName||t?.name))}
function compName(ev:Any){return text(ev?.league?.name||ev?.competitions?.[0]?.type?.text||ev?.competitions?.[0]?.type?.abbreviation||'Competizione')}
function compLogo(ev:Any){return ev?.league?.logos?.[0]?.href||ev?.league?.logo||ev?.competitions?.[0]?.league?.logos?.[0]?.href||null}
function status(ev:Any){const s=text(ev?.status?.type?.state||ev?.status?.type?.name).toLowerCase();if(s==='in'||s.includes('live'))return 'live';if(s==='post'||s.includes('final')||s.includes('complete'))return 'completed';return 'scheduled'}
function competitor(ev:Any){return arr(ev?.competitions?.[0]?.competitors)}
function eventToRow(ev:Any,userId:string,season:string){const cs=competitor(ev);const j=cs.find(isJuve),o=cs.find(x=>x!==j);if(!j||!o)return null;const home=j.homeAway==='home';return {user_id:userId,external_id:text(ev.id),season,competition:compName(ev),competition_logo_url:compLogo(ev),match_date:ev.date||null,opponent:o.team?.displayName||o.team?.name||'Avversario',opponent_logo_url:o.team?.logos?.[0]?.href||o.team?.logo||null,venue:ev?.competitions?.[0]?.venue?.fullName||ev?.competitions?.[0]?.venue?.address?.city||null,status:status(ev),juve_score:num(home?j.score:o.score),opponent_score:num(home?o.score:j.score),raw_provider_json:ev}}
function collectAthletes(obj:Any,out:Any[]=[]){if(!obj||typeof obj!=='object')return out;if(Array.isArray(obj)){obj.forEach(x=>collectAthletes(x,out));return out}const team= obj?.team || obj?.teamInfo; const athletes=obj?.athletes||obj?.players||obj?.roster; if(athletes&&isJuve(team)){arr(athletes).forEach((a:any)=>{const p=a?.athlete||a?.player||a;const name=p?.displayName||p?.fullName||p?.shortName;if(name)out.push({p,a})})}Object.values(obj).forEach(v=>{if(v&&typeof v==='object'&&v!==athletes)collectAthletes(v,out)});return out}
function lineup(summary:Any){const all=collectAthletes(summary);const map=new Map<string,Any>();for(const x of all){const p=x.p,a=x.a;const id=text(p?.id||a?.id||p?.displayName);if(id&&!map.has(id))map.set(id,{p,a})}return [...map.values()]}
function starter(a:Any){return a?.starter===true||a?.isStarter===true||/starter/i.test(text(a?.position?.displayName||a?.position?.name))}
function parseStats(obj:Any){const out:Record<string,number>={};const walk=(x:Any)=>{if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}if(x.name!=null&&(x.value!=null||x.displayValue!=null)){const k=text(x.name||x.displayName).toLowerCase();const n=Number(String(x.value??x.displayValue).replace('%','').replace(',','.'));if(Number.isFinite(n)){if(/possession/.test(k))out.possession=n;else if(/expected goals|(^| )xg($| )/.test(k))out.xg=n;else if(/shots on target/.test(k))out.shots_on_target=n;else if(/shots/.test(k))out.shots=n;else if(/corner/.test(k))out.corners=n;else if(/offsides/.test(k))out.offsides=n;else if(/successful passes|accurate passes/.test(k))out.successful_passes=n;else if(/passes/.test(k))out.passes=n;else if(/pass accuracy|passing accuracy/.test(k))out.pass_accuracy=n;else if(/tackles/.test(k))out.tackles=n;else if(/interceptions/.test(k))out.interceptions=n;else if(/fouls/.test(k))out.fouls=n;else if(/yellow/.test(k))out.yellow_cards=n;else if(/red/.test(k))out.red_cards=n;else if(/saves/.test(k))out.saves=n}}Object.values(x).forEach(v=>{if(v&&typeof v==='object')walk(v)})};walk(obj);return out}
function playerStats(summary:Any,name:string){const norm=(x:string)=>x.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');let found:any=null;const walk=(x:Any)=>{if(found||!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}const p=x?.athlete||x?.player;const n=p?.displayName||p?.fullName||x?.displayName||x?.name;if(n&&norm(n)===norm(name)&&(x.statistics||x.stats||x.details))found=parseStats(x.statistics||x.stats||x.details);Object.values(x).forEach(v=>{if(v&&typeof v==='object')walk(v)})};walk(summary);return found||{}}
function events(summary:Any){const out:any[]=[];const walk=(x:Any)=>{if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}const t=text(x?.type?.text||x?.type?.name||x?.type||x?.eventType).toLowerCase();const d=text(x?.text||x?.description||x?.shortText||x?.detail);const minute=x?.clock?.displayValue||x?.minute||x?.time?.displayValue;if((minute||d)&&/goal|score|card|yellow|red|substitution|substitute|penalty|var|own goal/.test(t+' '+d)){out.push({minute:text(minute),type:t,text:d,name:text(x?.athlete?.displayName||x?.player?.displayName||x?.playerName),team:text(x?.team?.displayName||x?.team?.name||x?.teamName)})}Object.values(x).forEach(v=>{if(v&&typeof v==='object')walk(v)})};walk(summary);return out.slice(0,100)}

export async function POST(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return NextResponse.json({error:'Non autenticato'},{status:401});
 const {data:settings}=await supabase.from('tracker_settings').select('season').eq('user_id',user.id).maybeSingle();
 const season=String(settings?.season||'2026/27'); const year=Number(season.slice(0,4))||2026;
 const run=(await supabase.from('sync_runs').insert({user_id:user.id,provider:'espn',status:'running'}).select('id').maybeSingle()).data?.id;
 try{
  const feeds=await Promise.all(LEAGUES.map(async l=>{try{return await get(`/${l}/scoreboard?limit=100&dates=${year}0101-${year+1}1231`)}catch{return {events:[]}}}));
  const all=new Map<string,Any>(); for(const f of feeds)for(const e of arr(f.events))if(competitor(e).some(isJuve))all.set(text(e.id),e);
  // Team schedule is the primary source because it also catches competitions not listed above.
  try{const s=await get(`/ita.1/teams/${JUVE_ID}/schedule`);for(const e of arr(s.events))if(competitor(e).some(isJuve))all.set(text(e.id),e)}catch{}
  const imported=[...all.values()].map(e=>eventToRow(e,user.id,season)).filter(Boolean).sort((a:any,b:any)=>String(a.match_date).localeCompare(String(b.match_date)));
  const {data:existing}=await supabase.from('matches').select('id,external_id,raw_provider_json').eq('user_id',user.id); const old=new Map((existing||[]).map((x:any)=>[text(x.external_id),x]));
  let saved=0,details=0;
  for(const row of imported as any[]){const {data:m,error}=await supabase.from('matches').upsert(row,{onConflict:'user_id,external_id'}).select('id').single();if(error||!m)continue;saved++;const oldm=old.get(text(row.external_id));const st=row.status;const need=st==='live'||(st==='completed'&&!oldm?.raw_provider_json?.__espnDetail);if(!need)continue;try{const sum=await get(`/ita.1/summary?event=${encodeURIComponent(row.external_id)}`);details++;await supabase.from('matches').update({status:status(sum),juve_score:row.juve_score,opponent_score:row.opponent_score,raw_provider_json:{...sum,__espnDetail:true}}).eq('id',m.id).eq('user_id',user.id);
    const ls=lineup(sum); const starters=ls.filter(x=>starter(x.a)).slice(0,11), bench=ls.filter(x=>!starter(x.a)).slice(0,12);
    for(const item of [...starters.map(x=>({...x,started:true})),...bench.map(x=>({...x,started:false}))]){const p=item.p,a=item.a;const ext=text(p?.id||a?.id);if(!ext)continue;const {data:ep}=await supabase.from('players').select('id').eq('user_id',user.id).eq('external_id',ext).maybeSingle();let pid=ep?.id;if(!pid){const pos=text(p?.position?.abbreviation||p?.position?.name||a?.position?.abbreviation||a?.position?.name);const role=/goal/i.test(pos)?'GK':/def/i.test(pos)?'DF':/mid/i.test(pos)?'MF':'FW';const ins=await supabase.from('players').insert({user_id:user.id,external_id:ext,name:p?.displayName||p?.fullName||'Giocatore',short_name:p?.shortName||p?.displayName||'Giocatore',number:num(p?.jersey||p?.shirtNumber),position:pos,role_group:role,photo_url:p?.headshot?.href||p?.photo||null,active:true}).select('id').single();pid=ins.data?.id}else await supabase.from('players').update({name:p?.displayName||p?.fullName,short_name:p?.shortName||p?.displayName,number:num(p?.jersey||p?.shirtNumber),photo_url:p?.headshot?.href||p?.photo||undefined,active:true}).eq('id',pid).eq('user_id',user.id);if(!pid)continue;const ps=playerStats(sum,p?.displayName||p?.fullName||'');const mins=num(a?.minutes||a?.minutesPlayed||ps.minutes)||0;await supabase.from('match_players').upsert({user_id:user.id,match_id:m.id,player_id:pid,started:item.started,bench:!item.started,minutes:mins},{onConflict:'match_id,player_id'});await supabase.from('player_match_stats').upsert({user_id:user.id,match_id:m.id,player_id:pid,appearances:mins>0?1:0,minutes:mins,goals:ps.goals||0,assists:ps.assists||0,shots:ps.shots||0,shots_on_target:ps.shots_on_target||0,xg:ps.xg??null,xa:null,chances_created:ps.key_passes||0,successful_dribbles:ps.successful_dribbles||0,duels_won:ps.duels_won||0,recoveries:ps.recoveries||ps.interceptions||0,yellow_cards:ps.yellow_cards||0,red_cards:ps.red_cards||0,raw_provider_json:item},{onConflict:'match_id,player_id'})}
    const ts=parseStats(sum);await supabase.from('match_team_stats').upsert({user_id:user.id,match_id:m.id,possession:ts.possession??null,xg:ts.xg??null,shots:ts.shots??null,shots_on_target:ts.shots_on_target??null,corners:ts.corners??null,offsides:ts.offsides??null,passes:ts.passes??null,successful_passes:ts.successful_passes??null,pass_accuracy:ts.pass_accuracy??null,tackles:ts.tackles??null,interceptions:ts.interceptions??null,fouls:ts.fouls??null,yellow_cards:ts.yellow_cards??null,red_cards:ts.red_cards??null,saves:ts.saves??null,raw_provider_json:{events:events(sum),stats:ts}},{onConflict:'match_id'});
   }catch{}
  }
  await supabase.from('tracker_settings').update({provider:'espn',season,updated_at:new Date().toISOString()}).eq('user_id',user.id);if(run)await supabase.from('sync_runs').update({status:'completed',finished_at:new Date().toISOString(),message:`${saved} partite sincronizzate, ${details} referti ESPN aggiornati`}).eq('id',run);return NextResponse.json({ok:true,provider:'espn',savedMatches:saved,detailedMatches:details});
 }catch(e:any){if(run)await supabase.from('sync_runs').update({status:'failed',finished_at:new Date().toISOString(),message:e?.message||'sync error'}).eq('id',run);return NextResponse.json({error:e?.message||'ESPN sync error'},{status:500})}
}
