import Link from 'next/link';
import {House,Plane,Radio,Trophy,Shield,CalendarDays} from 'lucide-react';
import {getUser} from '@/lib/data';
import {AutoRefresh} from './components_client';
import DashboardCalendar from './dashboard-client';
const JUVE='https://a.espncdn.com/i/teamlogos/soccer/500/111.png';
function result(m:any){if(m?.status!=='completed')return '';const a=Number(m.juve_score),b=Number(m.opponent_score);return a>b?'win':a===b?'draw':'loss'}
function homeOf(m:any){const raw=m?.raw_provider_json?.header?.competitions?.[0]?.competitors||[];return raw.find((c:any)=>String(c?.team?.id)==='111')?.homeAway==='home'}
function FormDots({matches}:{matches:any[]}){return <div className="form-strip compact">{matches.slice(0,5).map(m=><Link key={m.id} href={`/matches/${m.id}`} className={`form-dot ${result(m)}`} title={`${m.opponent} ${m.juve_score}-${m.opponent_score}`}><span>{result(m)==='win'?'V':result(m)==='draw'?'P':'S'}</span><small>{m.opponent}</small></Link>)}</div>}
function MatchCard({m,label,form}:{m:any,label:string,form?:any[]}){if(!m)return <div className="hero-match empty"><span>{label}</span><b>Nessuna partita</b></div>;const home=homeOf(m);const leftName=home?'Juventus':m.opponent;const rightName=home?m.opponent:'Juventus';const leftLogo=home?JUVE:m.opponent_logo_url;const rightLogo=home?m.opponent_logo_url:JUVE;const leftScore=home?m.juve_score:m.opponent_score;const rightScore=home?m.opponent_score:m.juve_score;return <Link href={`/matches/${m.id}`} className={`hero-match ${result(m)}`}><div className="hero-match-head"><span>{label}</span><small>{m.competition}</small></div><div className="hero-teams"><div><img src={leftLogo}/><b>{leftName}</b></div><strong>{leftScore!=null?`${leftScore} - ${rightScore}`:'VS'}</strong><div><img src={rightLogo}/><b>{rightName}</b></div></div><p>{new Date(m.match_date).toLocaleString('it-IT',{dateStyle:'medium',timeStyle:'short'})} · {home?<><House size={14}/> Casa</>:<><Plane size={14}/> Trasferta</>}</p>{form&&<><div className="next-form-label">ULTIME 5</div><FormDots matches={form}/></>}</Link>}
export default async function Dashboard(){const {supabase,user}=await getUser();if(!user)return null;const {data:matches}=await supabase.from('matches').select('*').eq('user_id',user.id).order('match_date',{ascending:true});const ms=matches||[];const completed=ms.filter(m=>m.status==='completed').sort((a,b)=>+new Date(b.match_date)-+new Date(a.match_date));const live=ms.find(m=>m.status==='live');const upcoming=ms.filter(m=>m.status!=='completed'&&m.status!=='live').sort((a,b)=>+new Date(a.match_date)-+new Date(b.match_date));const last=completed[0];const next=upcoming[0];return <div><AutoRefresh seconds={25} sync={true}/><header className="topbar"><div><p className="eyebrow">JUVENTUS TRACKER</p><h1>Dashboard</h1><p className="muted">Ultima, prossima, live e calendario Juventus.</p></div></header><section className="hero-two"><MatchCard m={last} label="ULTIMA PARTITA"/><MatchCard m={next} label="PROSSIMA PARTITA" form={completed}/></section><section className="panel live-panel"><div className="panel-head"><div><p className="eyebrow live-red">LIVE</p><h3>Partita live</h3></div></div>{live?<Link href={`/matches/${live.id}`} className="live-card"><span className="live-badge">LIVE</span><div><img src={homeOf(live)?JUVE:live.opponent_logo_url}/><b>{homeOf(live)?'Juventus':live.opponent}</b><strong>{homeOf(live)?`${live.juve_score??0} - ${live.opponent_score??0}`:`${live.opponent_score??0} - ${live.juve_score??0}`}</strong><img src={homeOf(live)?live.opponent_logo_url:JUVE}/><b>{homeOf(live)?live.opponent:'Juventus'}</b></div><small>{live.competition}</small></Link>:<div className="empty">La Juventus non sta giocando in questo momento.</div>}</section><DashboardCalendar matches={ms}/><section className="quick-grid"><Link href="/squad" className="quick-card"><Shield/><div><strong>Rosa</strong><span>Giocatori e allenatori</span></div></Link><Link href="/matches" className="quick-card"><CalendarDays/><div><strong>Partite</strong><span>Calendario e voti</span></div></Link><Link href="/stats" className="quick-card"><Trophy/><div><strong>Statistiche</strong><span>Juventus e giocatori</span></div></Link><Link href="/settings" className="quick-card"><Radio/><div><strong>Aggiornamento</strong><span>Automatico</span></div></Link></section></div>}
